
const arrFlightData = [
{"ID":"1","StadtKey":"altenburg","Start":"Altenburg","Start Flughafen":"AOC","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"2","StadtKey":"altenburg","Start":"Altenburg","Start Flughafen":"AOC","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"3","StadtKey":"altenburg","Start":"Altenburg","Start Flughafen":"AOC","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"4","StadtKey":"berlin-schoenefeld","Start":"Berlin-Schönefeld","Start Flughafen":"SXF","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:40"},
{"ID":"5","StadtKey":"berlin-schoenefeld","Start":"Berlin-Schönefeld","Start Flughafen":"SXF","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:40"},
{"ID":"6","StadtKey":"berlin-schoenefeld","Start":"Berlin-Schönefeld","Start Flughafen":"SXF","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"22:47"},
{"ID":"7","StadtKey":"berlin-tegel","Start":"Berlin-Tegel","Start Flughafen":"TXL","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:55"},
{"ID":"8","StadtKey":"berlin-tegel","Start":"Berlin-Tegel","Start Flughafen":"TXL","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"09:15"},
{"ID":"9","StadtKey":"berlin-tegel","Start":"Berlin-Tegel","Start Flughafen":"TXL","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:09"},
{"ID":"10","StadtKey":"braunschweig-wolfsburg","Start":"Braunschweig-Wolfsburg","Start Flughafen":"BWE","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"11","StadtKey":"braunschweig-wolfsburg","Start":"Braunschweig-Wolfsburg","Start Flughafen":"BWE","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"12","StadtKey":"braunschweig-wolfsburg","Start":"Braunschweig-Wolfsburg","Start Flughafen":"BWE","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"13","StadtKey":"bremen","Start":"Bremen","Start Flughafen":"BRE","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:45"},
{"ID":"14","StadtKey":"bremen","Start":"Bremen","Start Flughafen":"BRE","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:35"},
{"ID":"15","StadtKey":"bremen","Start":"Bremen","Start Flughafen":"BRE","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:43"},
{"ID":"16","StadtKey":"cuxhaven-nordholz","Start":"Cuxhaven Nordholz","Start Flughafen":"FCN","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"17","StadtKey":"cuxhaven-nordholz","Start":"Cuxhaven Nordholz","Start Flughafen":"FCN","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"18","StadtKey":"cuxhaven-nordholz","Start":"Cuxhaven Nordholz","Start Flughafen":"FCN","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"19","StadtKey":"dortmund","Start":"Dortmund","Start Flughafen":"DTM","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:20"},
{"ID":"20","StadtKey":"dortmund","Start":"Dortmund","Start Flughafen":"DTM","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"12:00"},
{"ID":"21","StadtKey":"dortmund","Start":"Dortmund","Start Flughafen":"DTM","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"16:53"},
{"ID":"22","StadtKey":"dresden","Start":"Dresden","Start Flughafen":"DRS","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:05"},
{"ID":"23","StadtKey":"dresden","Start":"Dresden","Start Flughafen":"DRS","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:20"},
{"ID":"24","StadtKey":"dresden","Start":"Dresden","Start Flughafen":"DRS","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"14:51"},
{"ID":"25","StadtKey":"duesseldorf","Start":"Düsseldorf","Start Flughafen":"DUS","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"08:50"},
{"ID":"26","StadtKey":"duesseldorf","Start":"Düsseldorf","Start Flughafen":"DUS","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"09:05"},
{"ID":"27","StadtKey":"duesseldorf","Start":"Düsseldorf","Start Flughafen":"DUS","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"12:51"},
{"ID":"28","StadtKey":"erfurt-weimar","Start":"Erfurt-Weimar","Start Flughafen":"ERF","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"29","StadtKey":"erfurt-weimar","Start":"Erfurt-Weimar","Start Flughafen":"ERF","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"30","StadtKey":"erfurt-weimar","Start":"Erfurt-Weimar","Start Flughafen":"ERF","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"31","StadtKey":"essen","Start":"Essen","Start Flughafen":"ESS","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"32","StadtKey":"essen","Start":"Essen","Start Flughafen":"ESS","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"33","StadtKey":"essen","Start":"Essen","Start Flughafen":"ESS","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"34","StadtKey":"frankfurtammain","Start":"Frankfurt am Main","Start Flughafen":"FRA","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"08:44"},
{"ID":"35","StadtKey":"frankfurtammain","Start":"Frankfurt am Main","Start Flughafen":"FRA","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"08:45"},
{"ID":"36","StadtKey":"frankfurtammain","Start":"Frankfurt am Main","Start Flughafen":"FRA","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:48"},
{"ID":"37","StadtKey":"frankfurt-hahn","Start":"Frankfurt-Hahn","Start Flughafen":"HHN","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"38","StadtKey":"frankfurt-hahn","Start":"Frankfurt-Hahn","Start Flughafen":"HHN","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"39","StadtKey":"frankfurt-hahn","Start":"Frankfurt-Hahn","Start Flughafen":"HHN","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"40","StadtKey":"friedrichshafen","Start":"Friedrichshafen","Start Flughafen":"FDH","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"12:00"},
{"ID":"41","StadtKey":"friedrichshafen","Start":"Friedrichshafen","Start Flughafen":"FDH","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:35"},
{"ID":"42","StadtKey":"friedrichshafen","Start":"Friedrichshafen","Start Flughafen":"FDH","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"14:58"},
{"ID":"43","StadtKey":"hamburg","Start":"Hamburg","Start Flughafen":"HAM","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:45"},
{"ID":"44","StadtKey":"hamburg","Start":"Hamburg","Start Flughafen":"HAM","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:50"},
{"ID":"45","StadtKey":"hamburg","Start":"Hamburg","Start Flughafen":"HAM","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:53"},
{"ID":"46","StadtKey":"hannover-langenhagen","Start":"Hannover-Langenhagen","Start Flughafen":"HAJ","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:30"},
{"ID":"47","StadtKey":"hannover-langenhagen","Start":"Hannover-Langenhagen","Start Flughafen":"HAJ","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:45"},
{"ID":"48","StadtKey":"hannover-langenhagen","Start":"Hannover-Langenhagen","Start Flughafen":"HAJ","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:48"},
{"ID":"49","StadtKey":"heringsdorf","Start":"Heringsdorf","Start Flughafen":"HDF","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"50","StadtKey":"heringsdorf","Start":"Heringsdorf","Start Flughafen":"HDF","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"51","StadtKey":"heringsdorf","Start":"Heringsdorf","Start Flughafen":"HDF","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"52","StadtKey":"hof-plauen","Start":"Hof-Plauen","Start Flughafen":"HOQ","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"53","StadtKey":"hof-plauen","Start":"Hof-Plauen","Start Flughafen":"HOQ","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"54","StadtKey":"hof-plauen","Start":"Hof-Plauen","Start Flughafen":"HOQ","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"55","StadtKey":"ingolstadt-manching","Start":"Ingolstadt Manching","Start Flughafen":"IGS","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"56","StadtKey":"ingolstadt-manching","Start":"Ingolstadt Manching","Start Flughafen":"IGS","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"57","StadtKey":"ingolstadt-manching","Start":"Ingolstadt Manching","Start Flughafen":"IGS","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"58","StadtKey":"karlsruhe-baden-baden","Start":"Karlsruhe Baden-Baden","Start Flughafen":"FKB","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"17:55"},
{"ID":"59","StadtKey":"karlsruhe-baden-baden","Start":"Karlsruhe Baden-Baden","Start Flughafen":"FKB","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"16:30"},
{"ID":"60","StadtKey":"karlsruhe-baden-baden","Start":"Karlsruhe Baden-Baden","Start Flughafen":"FKB","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"18:48"},
{"ID":"61","StadtKey":"kassel-calden","Start":"Kassel-Calden","Start Flughafen":"KSF","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"62","StadtKey":"kassel-calden","Start":"Kassel-Calden","Start Flughafen":"KSF","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"63","StadtKey":"kassel-calden","Start":"Kassel-Calden","Start Flughafen":"KSF","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"64","StadtKey":"koeln-bonn","Start":"Köln Bonn","Start Flughafen":"CGN","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:10"},
{"ID":"65","StadtKey":"koeln-bonn","Start":"Köln Bonn","Start Flughafen":"CGN","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:10"},
{"ID":"66","StadtKey":"koeln-bonn","Start":"Köln Bonn","Start Flughafen":"CGN","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:42"},
{"ID":"67","StadtKey":"lahr","Start":"Lahr","Start Flughafen":"LHA","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"68","StadtKey":"lahr","Start":"Lahr","Start Flughafen":"LHA","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"69","StadtKey":"lahr","Start":"Lahr","Start Flughafen":"LHA","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"70","StadtKey":"leipzig-halle","Start":"Leipzig Halle","Start Flughafen":"LEJ","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:10"},
{"ID":"71","StadtKey":"leipzig-halle","Start":"Leipzig Halle","Start Flughafen":"LEJ","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:40"},
{"ID":"72","StadtKey":"leipzig-halle","Start":"Leipzig Halle","Start Flughafen":"LEJ","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:46"},
{"ID":"73","StadtKey":"luebeck-blankensee","Start":"Lübeck-Blankensee","Start Flughafen":"LBC","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"74","StadtKey":"luebeck-blankensee","Start":"Lübeck-Blankensee","Start Flughafen":"LBC","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"75","StadtKey":"luebeck-blankensee","Start":"Lübeck-Blankensee","Start Flughafen":"LBC","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"76","StadtKey":"magdeburg-cochstedt","Start":"Magdeburg-Cochstedt","Start Flughafen":"CSO","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"77","StadtKey":"magdeburg-cochstedt","Start":"Magdeburg-Cochstedt","Start Flughafen":"CSO","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"78","StadtKey":"magdeburg-cochstedt","Start":"Magdeburg-Cochstedt","Start Flughafen":"CSO","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"79","StadtKey":"mannheim","Start":"Mannheim","Start Flughafen":"MHG","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"80","StadtKey":"mannheim","Start":"Mannheim","Start Flughafen":"MHG","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"81","StadtKey":"mannheim","Start":"Mannheim","Start Flughafen":"MHG","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"82","StadtKey":"memmingen","Start":"Memmingen","Start Flughafen":"FMM","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"83","StadtKey":"memmingen","Start":"Memmingen","Start Flughafen":"FMM","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"84","StadtKey":"memmingen","Start":"Memmingen","Start Flughafen":"FMM","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"85","StadtKey":"moenchengladbach","Start":"Mönchengladbach","Start Flughafen":"MGL","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"86","StadtKey":"moenchengladbach","Start":"Mönchengladbach","Start Flughafen":"MGL","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"87","StadtKey":"moenchengladbach","Start":"Mönchengladbach","Start Flughafen":"MGL","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"88","StadtKey":"muenchen","Start":"München","Start Flughafen":"MUC","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"09:30"},
{"ID":"89","StadtKey":"muenchen","Start":"München","Start Flughafen":"MUC","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Ja","Kürzeste Dauer (Std.)*":"09:25"},
{"ID":"90","StadtKey":"muenchen","Start":"München","Start Flughafen":"MUC","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:53"},
{"ID":"91","StadtKey":"muenster-osnabrueck","Start":"Münster Osnabrück","Start Flughafen":"FMO","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:55"},
{"ID":"92","StadtKey":"muenster-osnabrueck","Start":"Münster Osnabrück","Start Flughafen":"FMO","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:30"},
{"ID":"93","StadtKey":"muenster-osnabrueck","Start":"Münster Osnabrück","Start Flughafen":"FMO","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"14:58"},
{"ID":"94","StadtKey":"neubrandenburg","Start":"Neubrandenburg","Start Flughafen":"FNB","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"95","StadtKey":"neubrandenburg","Start":"Neubrandenburg","Start Flughafen":"FNB","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"96","StadtKey":"neubrandenburg","Start":"Neubrandenburg","Start Flughafen":"FNB","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"97","StadtKey":"nuernberg","Start":"Nürnberg","Start Flughafen":"NUE","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:55"},
{"ID":"98","StadtKey":"nuernberg","Start":"Nürnberg","Start Flughafen":"NUE","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:35"},
{"ID":"99","StadtKey":"nuernberg","Start":"Nürnberg","Start Flughafen":"NUE","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:51"},
{"ID":"100","StadtKey":"oberpfaffenhofen","Start":"Oberpfaffenhofen","Start Flughafen":"OBF","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"101","StadtKey":"oberpfaffenhofen","Start":"Oberpfaffenhofen","Start Flughafen":"OBF","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"102","StadtKey":"oberpfaffenhofen","Start":"Oberpfaffenhofen","Start Flughafen":"OBF","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"103","StadtKey":"paderborn-lippstadt","Start":"Paderborn Lippstadt","Start Flughafen":"PAD","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"12:05"},
{"ID":"104","StadtKey":"paderborn-lippstadt","Start":"Paderborn Lippstadt","Start Flughafen":"PAD","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:55"},
{"ID":"105","StadtKey":"paderborn-lippstadt","Start":"Paderborn Lippstadt","Start Flughafen":"PAD","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"14:08"},
{"ID":"106","StadtKey":"rostock-laage","Start":"Rostock-Laage","Start Flughafen":"RLG","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"107","StadtKey":"rostock-laage","Start":"Rostock-Laage","Start Flughafen":"RLG","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"108","StadtKey":"rostock-laage","Start":"Rostock-Laage","Start Flughafen":"RLG","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"109","StadtKey":"saarbruecken","Start":"Saarbrücken","Start Flughafen":"SCN","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"110","StadtKey":"saarbruecken","Start":"Saarbrücken","Start Flughafen":"SCN","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"111","StadtKey":"saarbruecken","Start":"Saarbrücken","Start Flughafen":"SCN","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"112","StadtKey":"schwerin-parchim","Start":"Schwerin-Parchim","Start Flughafen":"SZW","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"113","StadtKey":"schwerin-parchim","Start":"Schwerin-Parchim","Start Flughafen":"SZW","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"114","StadtKey":"schwerin-parchim","Start":"Schwerin-Parchim","Start Flughafen":"SZW","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"115","StadtKey":"siegerland","Start":"Siegerland","Start Flughafen":"SGE","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"116","StadtKey":"siegerland","Start":"Siegerland","Start Flughafen":"SGE","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"117","StadtKey":"siegerland","Start":"Siegerland","Start Flughafen":"SGE","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"118","StadtKey":"stralsund-barth","Start":"Stralsund-Barth","Start Flughafen":"BBH","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"119","StadtKey":"stralsund-barth","Start":"Stralsund-Barth","Start Flughafen":"BBH","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"120","StadtKey":"stralsund-barth","Start":"Stralsund-Barth","Start Flughafen":"BBH","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"121","StadtKey":"stuttgart","Start":"Stuttgart","Start Flughafen":"STR","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"10:40"},
{"ID":"122","StadtKey":"stuttgart","Start":"Stuttgart","Start Flughafen":"STR","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:05"},
{"ID":"123","StadtKey":"stuttgart","Start":"Stuttgart","Start Flughafen":"STR","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"13:16"},
{"ID":"124","StadtKey":"sylt-westerland","Start":"Sylt, Westerland","Start Flughafen":"GWT","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"12:55"},
{"ID":"125","StadtKey":"sylt-westerland","Start":"Sylt, Westerland","Start Flughafen":"GWT","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"11:50"},
{"ID":"126","StadtKey":"sylt-westerland","Start":"Sylt, Westerland","Start Flughafen":"GWT","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"15:16"},
{"ID":"127","StadtKey":"weeze-niederrhein","Start":"Weeze, Niederrhein","Start Flughafen":"NRN","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"128","StadtKey":"weeze-niederrhein","Start":"Weeze, Niederrhein","Start Flughafen":"NRN","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"129","StadtKey":"weeze-niederrhein","Start":"Weeze, Niederrhein","Start Flughafen":"NRN","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"130","StadtKey":"zweibruecken","Start":"Zweibrücken","Start Flughafen":"ZQW","Ziel":"New York City","Ziel Flughafen":"JFK","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"131","StadtKey":"zweibruecken","Start":"Zweibrücken","Start Flughafen":"ZQW","Ziel":"New York City","Ziel Flughafen":"EWR","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"},
{"ID":"132","StadtKey":"zweibruecken","Start":"Zweibrücken","Start Flughafen":"ZQW","Ziel":"New York City","Ziel Flughafen":"LGA","Nonstop":"Nein","Kürzeste Dauer (Std.)*":"Kein Flug"}
];

export function getFlightData() {
    return arrFlightData;
}

